#
# docker-compose.yml
#
services:
  #
  # server app.
  #
  bc-meeting_server:
    container_name: bc-meeting_server
    build:
      context: ../bc-meeting_server
      dockerfile: Dockerfile
    ports:
      - 3100:3100
    networks:
      - backend
    environment:
      # Database (MySQL)
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DBNAME: ${DATABASE_DBNAME}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl http://localhost:3100/api || exit 1']
      start_period: 3s
      retries: 3
      timeout: 1s
      interval: 1s

  #
  # client app.
  #
  bc-meeting_client:
    container_name: bc-meeting_client
    build:
      context: ../bc-meeting_client
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/log:/var/log/nginx
    networks:
      - backend
    depends_on:
      bc-meeting_server:
        condition: service_healthy

networks:
  backend: {}
